version: '3'

services:
  utsc_coin_miner_1:
    build:
      context: ./miner1/miner
    container_name: utsc_coin_miner_1
    network_mode: "host"
    ports:
      - '8000:8000'
    volumes:
      - ./miner1/miner/core:/app/core

  utsc_coin_miner_2:
    build:
      context: ./miner2/miner
    container_name: utsc_coin_miner_2
    network_mode: "host"
    ports: 
      - '8001:8001'
    volumes:
      - ./miner2/miner/core:/app/core
