version: '3'

services:
  ucm_master:
    build:
      context: ./master
    container_name: ucm_master
    network_mode: 'host'
    ports:
      - '8000:8000'
    environment:
      - MINER_PORT=8000
    volumes:
      - ./master/core:/app/core
      - ./master/blockchain:/app/blockchain
      - ./master/wallet:/app/wallet
    env_file:
      - ./master/.env

  ucm_1:
    build:
      context: ./master
    container_name: ucm_1
    network_mode: 'host'
    ports:
      - '8001:8001'
    environment:
      - MINER_PORT=8001
    depends_on:
      - 'ucm_master'
    volumes:
      - ./master/core:/app/core
      - ./miner1/blockchain:/app/blockchain
      - ./miner1/wallet:/app/wallet
    env_file:
      - ./master/.env
