version: '3'

services:
  utsc_coin_miner_1:
    build:
      context: ./miner
    container_name: utsc_coin_miner_1
    networks:
      - nic
    ports:
      - '8000:8000'
    volumes:
      - ./miner/core:/app/core

  utsc_coin_miner_2:
    build:
      context: ./miner2
    container_name: utsc_coin_miner_2
    networks:
      - nic
    ports: 
      - '8001:8001'
    volumes:
      - ./miner2/core:/app/core

network:
  coin:
    driver: bridge
  

  

